### ISSUE TITLE
Formazioni gruppi di lavoro

### ISSUE THREAD

**Issue by mancusoa74** [mancusoa74/canteena#1]
Per svolgere le varie attività suddividiamo il team in **4 gruppi di lavoro**.

E' richiesto:
1. la lista dei gruppi con i componenti
2. l'indicazione di un single point of contact per ciascun gruppo

**Comment by ITdario** [comment]
Il team è formato da:

- @Williamjr223 (Viteritti)
- @MatteoSolavagione (Solavagione)
- @Pierpaolo05 (Quijada Gomez)
- @TheLuke0 (Bortoluzzi)
- @ITdario (Ruggieri)
Come punto di cui occuparsi abbiamo scelto: "interfaccia per api per lista utenti serviti"
Grazie. Buona giornata.

**Comment by mancusoa74** [comment]
la issue va chiusa quando la lista di tutti i grupopi di lavoro è pronta

**Comment by mancusoa74** [comment]
@ITdario 

> Il team è formato da:
> 
> * @Williamjr223 (Viteritti)
> * @MatteoSolavagione (Solavagione)
> * @Pierpaolo05 (Quijada Gomez)
> * @TheLuke0 (Bortoluzzi)
> * @ITdario (Ruggieri)
>   Come punto di cui occuparsi abbiamo scelto: "interfaccia per api per lista utenti serviti"
>   Grazie. Buona giornata.

la richiesta di questa issue è articolata in 2 punti.
bisogna fornire le informazioni  come richiesto

**Comment by mancusoa74** [comment]
avete la lista dei gruppi e il single point of contact per ciascun gruppo?

**Comment by mancusoa74** [comment]
non siete riscuti a formare i gruppi.

ciò significa che la possibilità che vi concedo di creare i gruppi in modo spontanea non è riconosciuta.

dalla prossima volta i gruppi li creo :(
