### ISSUE TITLE
fare lo screenshot dell'aggiunta di 3 prenotazioni alla mensa per 3 alunni diversi

### ISSUE THREAD

**Issue by Matteo-Solavagione** [mancusoa74/canteena#117]

**Comment by mancusoa74** [comment]
perchè hai aperto questa issue?

per cortesia cancellala.  per questo compito ti avevo assegnato una issue specifica.

elimina  questa issue in quanto non è necessaria

**Comment by mancusoa74** [comment]
perchè hai aperto questa issue?

per cortesia cancellala. per questo compito ti avevo assegnato una issue specifica.

**Comment by mancusoa74** [comment]
questa issue va cancellata
